// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGjRR-0QnToMjA8FUDMyQZORnYnYcILTE',
    appId: '1:639989890070:web:ca19465f0934dc953b8937',
    messagingSenderId: '639989890070',
    projectId: 'skillup-b8d78',
    authDomain: 'skillup-b8d78.firebaseapp.com',
    storageBucket: 'skillup-b8d78.appspot.com',
    measurementId: 'G-S5VCJ06KJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqBJe8aEJghHh8vA_Z17XJTzAlTE6Ta5k',
    appId: '1:639989890070:android:53f2f1def14f1e533b8937',
    messagingSenderId: '639989890070',
    projectId: 'skillup-b8d78',
    storageBucket: 'skillup-b8d78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVmF4v3MQ2--bDBYxSntw8S60RsndhakU',
    appId: '1:639989890070:ios:408ed0b4d49a2ec43b8937',
    messagingSenderId: '639989890070',
    projectId: 'skillup-b8d78',
    storageBucket: 'skillup-b8d78.appspot.com',
    iosBundleId: 'com.example.skillup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVmF4v3MQ2--bDBYxSntw8S60RsndhakU',
    appId: '1:639989890070:ios:408ed0b4d49a2ec43b8937',
    messagingSenderId: '639989890070',
    projectId: 'skillup-b8d78',
    storageBucket: 'skillup-b8d78.appspot.com',
    iosBundleId: 'com.example.skillup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGjRR-0QnToMjA8FUDMyQZORnYnYcILTE',
    appId: '1:639989890070:web:af48006c2d9fffa53b8937',
    messagingSenderId: '639989890070',
    projectId: 'skillup-b8d78',
    authDomain: 'skillup-b8d78.firebaseapp.com',
    storageBucket: 'skillup-b8d78.appspot.com',
    measurementId: 'G-7NBQ36REMN',
  );
}
